### ISSUE TITLE
Odd shell boilerplate

### ISSUE THREAD

**Issue by isiahmeadows** [scott113341/npm-install-version#5]
I noticed you're using `shx`, which might be helpful with npm-based build systems, but instead of using `shx rm -rf`, `shx mkdir -p`, `shx mv`, etc., you could use [`rimraf.sync`](http://npm.im/rimraf), [`mkdirp.sync`](http://npm.im/mkdirp), `fs.renameSync`, etc. to avoid the extra `exec` overhead. And if you need the ability to copy across partitions, [ShellJS already uses an easy workaround](https://github.com/shelljs/shelljs/blob/master/src/mv.js#L77-L85).

Oh, and just another suggestion, but take it or leave it: use `spawnSync` for the `npm` calls, so if someone uses `niv 'package@1 package@2'`, `npm` should error out, but does weird things instead.

**Comment by scott113341** [comment]
Thanks @isiahmeadows, you are completely right!  Check out #6 if you have a chance; I think both issues have been addressed.

I went with regular ShellJS commands like `shelljs.rm`, `shelljs.mkdir`, etc. instead of the packages you mentioned just because I am more familiar with ShellJS.  If there is a compelling reason to use those other modules I'm happy to switch.

I also replaced all usage of `execSync` with `spawnSync`, since in every case `spawnSync` was a better choice.
